#!/usr/bin/env python3
"""
HCM — Excel Model + PDF Report Generator
Auto-generated by generate_stock_model_builder.py on 2026-07-05 08:28
Company: Ho Chi Minh City Securities Corporation
Sector: Chứng khoán
Price at generation: 28,550.0 VND
"""
# ⚠ This file was auto-generated by AI. Review assumptions before using in production.

#!/usr/bin/env python3
"""
HCM (Ho Chi Minh City Securities Corporation) — Excel Model + PDF Report Generator
July 2026 | Framework FA 6 tầng + Skill Chứng khoán
"""

import os
import re
import json
import math
import subprocess
import tempfile
import threading
from datetime import datetime, date, timedelta
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side, numbers
from openpyxl.chart import BarChart, LineChart, Reference
from openpyxl.chart.series import SeriesLabel
from openpyxl.chart.label import DataLabelList
from openpyxl.utils import get_column_letter
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np
from scipy.interpolate import PchipInterpolator # Not strictly needed for this task, but good to keep from template
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm, cm
from reportlab.lib.colors import HexColor, black, white, grey
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                 TableStyle, PageBreak, Image, KeepTogether)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT, TA_JUSTIFY
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import requests
import statistics as stats

# ── OUTPUT ──────────────────────────────────────────────────────────────────
TICKER = "HCM"
COMPANY = "Ho Chi Minh City Securities Corporation"
SECTOR = "Chứng khoán"
EXCHANGE = "HOSE" # Assuming HOSE for a major securities company

# Analysis Month: 2026-07 from prompt. Use a fixed date for consistency with the prompt's context.
ANALYSIS_DATETIME = datetime(2026, 7, 5, 8, 26) # Example date from prompt: "05/07/2026 08:26"
MONTH_FOR_FILENAME = ANALYSIS_DATETIME.strftime("%Y-%m")

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Bao cao", TICKER)
EXCEL_FILE = os.path.join(OUT_DIR, f"{TICKER}_Model_{MONTH_FOR_FILENAME}.xlsx")
PDF_FILE   = os.path.join(OUT_DIR, f"{TICKER}_Phan_Tich_{MONTH_FOR_FILENAME}.pdf")
CHART_DIR  = os.path.join(OUT_DIR, "charts")
os.makedirs(CHART_DIR, exist_ok=True)

# ── DATA ────────────────────────────────